version: '3'
services:
  web:
    image: nginx:alpine
    container_name: web-master
    ports: ["80:80"]
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
  db:
    image: mysql:5.7
    container_name: db-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diplom_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: ["3306:3306"]
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - db_data:/var/lib/mysql
volumes:
  db_data: